#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
apply_ismay_ui_today_inbox_v1.py

目的：
  Capture業務API(前回パッチ)を実際にブラウザから目視・操作できるようにする、
  最初の2画面を実装する。
  - UI-03 ホーム／今日  (/today)
  - UI-04 Inbox         (/inbox)

  画面UX設計書・ワイヤーフレームv2.1のデザイントークン(配色・フォント)を
  Tailwind v4のCSS変数として取り込み、実際にAPIを叩く動くコンポーネントとして実装する。

前提・スコープ（正直に明記）：
  - UI-03の「今やる一つ」は、Responsibility API・Planning API(/planning/now)が
    未実装のため、実データを表示できない。設計書5章「共通状態／Empty」の指針
    (「何もありません」ではなく次の一手を提案する)に従い、正直な空状態＋
    Inboxへの導線を表示するに留める。
  - UI-04 InboxのAI候補欄は、AI Workerが未実装のため常に空で表示される
    (解析要求ボタン自体はCapture APIのanalyzeエンドポイントに実際に繋がっている)。
  - UI-05〜UI-15、認証必須ガード以外のナビゲーション項目は本パッチのスコープ外。

変更内容：
  1) globals.css / layout.tsx : ISMAY設計トークン(色・フォント)を反映
     (create-next-appデフォルトのGeist/汎用配色から置き換え)
  2) page.tsx : create-next-appデフォルトのボイラープレートから
     /todayへのリダイレクトへ置き換え(未着手だったルートページの着手)
  3) DashboardClient.tsx : "今日の画面へ"導線を追加(既存動作に影響しない追記)
  4) 新規:
     - src/components/app/AppShell.tsx        共通シェル(サイドバー・認証ガード)
     - src/components/capture/QuickCaptureForm.tsx  クイック入力(両画面で使用)
     - src/components/capture/InboxClient.tsx  UI-04本体
     - src/components/capture/TodayClient.tsx  UI-03本体
     - src/app/inbox/page.tsx
     - src/app/today/page.tsx

  スキーマ変更は無いため、prisma関連ステップは実行しない。
  tsc --noEmitがエラー0件の場合のみGitHubへpushする。
  (Next.js Fast Refreshが有効なため、成功後のサービス再起動は不要)

実行方法（サーバー側 ~/projects/ismay で）：
  python3 apply_ismay_ui_today_inbox_v1.py
"""

import subprocess
import sys
import shutil
from pathlib import Path
from datetime import datetime

BASE_DIR = Path.cwd()
APP_DIR = BASE_DIR / "app"
SRC_DIR = APP_DIR / "src"

GLOBALS_CSS_PATH = SRC_DIR / "app" / "globals.css"
LAYOUT_PATH = SRC_DIR / "app" / "layout.tsx"
PAGE_PATH = SRC_DIR / "app" / "page.tsx"
DASHBOARD_CLIENT_PATH = SRC_DIR / "components" / "auth" / "DashboardClient.tsx"

APP_SHELL_PATH = SRC_DIR / "components" / "app" / "AppShell.tsx"
QUICK_CAPTURE_PATH = SRC_DIR / "components" / "capture" / "QuickCaptureForm.tsx"
INBOX_CLIENT_PATH = SRC_DIR / "components" / "capture" / "InboxClient.tsx"
TODAY_CLIENT_PATH = SRC_DIR / "components" / "capture" / "TodayClient.tsx"
INBOX_PAGE_PATH = SRC_DIR / "app" / "inbox" / "page.tsx"
TODAY_PAGE_PATH = SRC_DIR / "app" / "today" / "page.tsx"

TIMESTAMP = datetime.now().strftime("%Y%m%d_%H%M%S")

created_files: list[Path] = []
backup_files: list[tuple[Path, Path]] = []


def fail(step: str, detail: str = "") -> None:
    print(f"\n[FAIL] {step}")
    if detail:
        print(detail)
    print("\n--- ロールバック手順 ---")
    for orig, backup in backup_files:
        print(f"  cp {backup} {orig}")
    for f in created_files:
        print(f"  rm {f}")
    print("pushは実行していません。GitHub上のコードは変更されていません。")
    sys.exit(1)


def run(cmd: list[str], cwd: Path, step: str) -> str:
    print(f"\n[RUN] ({cwd}) $ {' '.join(cmd)}")
    result = subprocess.run(cmd, cwd=str(cwd), capture_output=True, text=True)
    print(result.stdout[-4000:])
    if result.returncode != 0:
        print(result.stderr[-4000:])
        fail(step, result.stderr[-4000:] or result.stdout[-4000:])
    return result.stdout


def backup(path: Path) -> None:
    backup_path = path.with_name(f"{path.name}.bak_{TIMESTAMP}")
    shutil.copy2(path, backup_path)
    backup_files.append((path, backup_path))
    print(f"[BACKUP] {path} -> {backup_path}")


def write_new_file(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    created_files.append(path)
    print(f"[CREATE] {path}")


# ---------------------------------------------------------------------------
# 既存ファイルの現況(想定と一致するかの確認用)
# ---------------------------------------------------------------------------

ORIGINAL_GLOBALS_CSS = '''@import "tailwindcss";

:root {
  --background: #ffffff;
  --foreground: #171717;
}

@theme inline {
  --color-background: var(--background);
  --color-foreground: var(--foreground);
  --font-sans: var(--font-geist-sans);
  --font-mono: var(--font-geist-mono);
}

@media (prefers-color-scheme: dark) {
  :root {
    --background: #0a0a0a;
    --foreground: #ededed;
  }
}

body {
  background: var(--background);
  color: var(--foreground);
  font-family: Arial, Helvetica, sans-serif;
}'''

ORIGINAL_LAYOUT_TSX = '''import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}'''

PAGE_TSX_MARKER = "To get started, edit the"

DASHBOARD_IMPORT_MARKER = '''import { useEffect, useState, useCallback } from "react";
import { useRouter } from "next/navigation";
import { apiFetch } from "@/lib/auth/client";'''

DASHBOARD_IMPORT_REPLACEMENT = '''import { useEffect, useState, useCallback } from "react";
import { useRouter } from "next/navigation";
import Link from "next/link";
import { apiFetch } from "@/lib/auth/client";'''

DASHBOARD_HEADER_MARKER = '''      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-xl font-bold text-slate-800">{me.user.displayName ?? me.user.email}</h1>
          <p className="text-sm text-slate-500">{me.user.email}</p>
        </div>
        <button onClick={logout} className="text-sm text-slate-500 hover:text-slate-800 underline">
          ログアウト
        </button>
      </div>'''

DASHBOARD_HEADER_REPLACEMENT = '''      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-xl font-bold text-slate-800">{me.user.displayName ?? me.user.email}</h1>
          <p className="text-sm text-slate-500">{me.user.email}</p>
        </div>
        <div className="flex items-center gap-4">
          <Link href="/today" className="text-sm text-slate-500 hover:text-slate-800 underline">
            今日の画面へ
          </Link>
          <button onClick={logout} className="text-sm text-slate-500 hover:text-slate-800 underline">
            ログアウト
          </button>
        </div>
      </div>'''


def check_preconditions() -> None:
    print("=== 事前チェック ===")
    for p in [GLOBALS_CSS_PATH, LAYOUT_PATH, PAGE_PATH, DASHBOARD_CLIENT_PATH]:
        if not p.exists():
            fail("事前チェック", f"想定ファイルが見つかりません: {p}\n"
                                  "このスクリプトはリポジトリルート(~/projects/ismay)で実行してください。")

    if GLOBALS_CSS_PATH.read_text(encoding="utf-8").strip() != ORIGINAL_GLOBALS_CSS.strip():
        fail("事前チェック", "globals.cssが想定と異なります。GitHub上のコードが前回セッションから"
                              "変更されている可能性があるため、推測での適用を避けて中断します。")
    if LAYOUT_PATH.read_text(encoding="utf-8").strip() != ORIGINAL_LAYOUT_TSX.strip():
        fail("事前チェック", "layout.tsxが想定と異なります。中断します。")
    if PAGE_TSX_MARKER not in PAGE_PATH.read_text(encoding="utf-8"):
        fail("事前チェック", "page.tsxが想定(create-next-appデフォルト)と異なります。中断します。")
    dashboard_text = DASHBOARD_CLIENT_PATH.read_text(encoding="utf-8")
    if DASHBOARD_IMPORT_MARKER not in dashboard_text or DASHBOARD_HEADER_MARKER not in dashboard_text:
        fail("事前チェック", "DashboardClient.tsxの想定テキストが見つかりません。中断します。")

    for p in [APP_SHELL_PATH, QUICK_CAPTURE_PATH, INBOX_CLIENT_PATH, TODAY_CLIENT_PATH,
              INBOX_PAGE_PATH, TODAY_PAGE_PATH]:
        if p.exists():
            fail("事前チェック", f"{p} が既に存在します。二重適用を避けるため中断します。")

    print("[OK] 事前チェック完了。想定通りの現行コードであることを確認しました。")


# ---------------------------------------------------------------------------
# 新しいファイル内容
# ---------------------------------------------------------------------------

NEW_GLOBALS_CSS = '''@import "tailwindcss";

/* ISMAY 画面UX設計書・ワイヤーフレームv2.1のデザイントークンを反映。
   ダークモードは同設計書で定義されていないため単一(ライト)テーマとする。 */

:root {
  --background: #F5F6F3;
  --foreground: #14181F;
}

@theme inline {
  --color-background: var(--background);
  --color-foreground: var(--foreground);
  --font-sans: var(--font-inter);
  --font-mono: var(--font-plex-mono);
  --font-serif: var(--font-newsreader);

  --color-ink: #14181F;
  --color-muted: #6B7280;
  --color-faint: #9CA3AF;
  --color-canvas: #F5F6F3;
  --color-surface: #FFFFFF;
  --color-line: #E5E5E0;

  --color-brand: #2F5D62;
  --color-brand-50: #EEF4F3;
  --color-brand-100: #D9E7E5;
  --color-brand-600: #2F5D62;
  --color-brand-700: #234548;

  --color-ai: #6D28D9;
  --color-ai-50: #F3EEFC;
  --color-ai-100: #E6DBF9;

  --color-warn: #C2410C;
  --color-warn-50: #FDF0E9;

  --color-decide: #B45309;
  --color-decide-50: #FDF3E6;

  --color-safe: #15803D;
  --color-safe-50: #EBF6EF;

  --shadow-card: 0 1px 2px rgba(20,24,31,0.04), 0 1px 8px rgba(20,24,31,0.04);
  --shadow-pop: 0 8px 24px rgba(20,24,31,0.10);
}

body {
  background: var(--background);
  color: var(--foreground);
  font-family: var(--font-sans), sans-serif;
}
'''

NEW_LAYOUT_TSX = '''import type { Metadata } from "next";
import { Newsreader, Inter, IBM_Plex_Mono } from "next/font/google";
import "./globals.css";

const newsreader = Newsreader({
  variable: "--font-newsreader",
  subsets: ["latin"],
  style: ["normal", "italic"],
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const plexMono = IBM_Plex_Mono({
  variable: "--font-plex-mono",
  subsets: ["latin"],
  weight: ["400", "500"],
});

export const metadata: Metadata = {
  title: "ISMAY",
  description: "雑な入力から、まだタスクになっていない約束・責任を発見するAI個人参謀",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="ja"
      className={`${newsreader.variable} ${inter.variable} ${plexMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col bg-canvas text-ink">{children}</body>
    </html>
  );
}
'''

NEW_PAGE_TSX = '''import { redirect } from "next/navigation";

export default function Home() {
  redirect("/today");
}
'''

APP_SHELL_CONTENT = '''"use client";

import { useEffect, useState, type ReactNode } from "react";
import { useRouter, usePathname } from "next/navigation";

const NAV_ITEMS = [
  { href: "/today", label: "今日" },
  { href: "/inbox", label: "Inbox" },
] as const;

/**
 * 認証必須画面の共通シェル。/api/v1/auth/me で認証確認し、
 * 未認証なら/loginへリダイレクトする(DashboardClientと同じガード方針)。
 */
export function AppShell({ children }: { children: ReactNode }) {
  const router = useRouter();
  const pathname = usePathname();
  const [ready, setReady] = useState(false);

  useEffect(() => {
    let active = true;
    fetch("/api/v1/auth/me").then((res) => {
      if (!active) return;
      if (!res.ok) {
        router.replace("/login");
        return;
      }
      setReady(true);
    });
    return () => {
      active = false;
    };
  }, [router]);

  if (!ready) {
    return (
      <div className="min-h-screen flex items-center justify-center text-sm text-muted">
        読み込み中...
      </div>
    );
  }

  return (
    <div className="flex min-h-screen bg-canvas text-ink">
      <aside className="w-[220px] shrink-0 bg-surface border-r border-line hidden md:flex md:flex-col">
        <div className="h-16 flex items-center gap-2 px-5 border-b border-line">
          <div className="w-7 h-7 rounded-lg bg-brand flex items-center justify-center">
            <span className="text-white font-serif text-sm italic">i</span>
          </div>
          <span className="font-serif italic text-lg text-ink">Ismay</span>
        </div>
        <nav className="flex-1 px-3 py-4 space-y-1 text-sm">
          {NAV_ITEMS.map((item) => {
            const active = pathname === item.href;
            return (
              <button
                key={item.href}
                onClick={() => router.push(item.href)}
                className={`w-full text-left px-3 py-2 rounded-lg transition ${
                  active ? "bg-brand-50 text-brand-700 font-semibold" : "text-ink hover:bg-canvas"
                }`}
              >
                {item.label}
              </button>
            );
          })}
        </nav>
        <div className="px-3 py-4 border-t border-line">
          <button
            onClick={() => router.push("/dashboard")}
            className="w-full text-left px-3 py-2 rounded-lg text-sm text-muted hover:bg-canvas"
          >
            アカウント設定
          </button>
        </div>
      </aside>
      <main className="flex-1 min-w-0 overflow-y-auto">
        <div className="max-w-5xl mx-auto px-5 py-8 md:px-8">{children}</div>
      </main>
    </div>
  );
}
'''

QUICK_CAPTURE_CONTENT = '''"use client";

import { useState } from "react";
import { apiFetch } from "@/lib/auth/client";

/**
 * UX原則「Capture First」: 分類・期限なしで10秒以内に保存できる入口。
 * どの主要画面からも同じ形で使えるよう共通コンポーネント化している。
 */
export function QuickCaptureForm({ onCreated }: { onCreated?: () => void }) {
  const [text, setText] = useState("");
  const [submitting, setSubmitting] = useState(false);
  const [error, setError] = useState("");

  async function submit(e: React.FormEvent) {
    e.preventDefault();
    if (!text.trim() || submitting) return;
    setSubmitting(true);
    setError("");
    try {
      const res = await apiFetch("/api/v1/captures", {
        method: "POST",
        body: JSON.stringify({
          sourceType: "TEXT",
          rawText: text.trim(),
          clientDraftId: crypto.randomUUID(),
        }),
      });
      const body = await res.json();
      if (!res.ok) {
        setError(body.error?.message ?? "保存に失敗しました");
        return;
      }
      setText("");
      onCreated?.();
    } finally {
      setSubmitting(false);
    }
  }

  return (
    <form onSubmit={submit} className="bg-surface border border-line rounded-2xl shadow-card p-4">
      <textarea
        value={text}
        onChange={(e) => setText(e.target.value)}
        placeholder="話す・メモする…（約束、気になっていること、判断が必要なことなど）"
        rows={3}
        className="w-full resize-none bg-transparent text-sm focus:outline-none placeholder:text-faint"
      />
      <div className="flex items-center justify-between mt-2 gap-3">
        <p className="text-[11px] text-faint">分類や期限は不要です。あとからInboxで整理できます</p>
        <button
          type="submit"
          disabled={submitting || !text.trim()}
          className="shrink-0 bg-ink text-white text-sm font-medium px-4 py-2 rounded-xl disabled:opacity-40 hover:bg-black transition"
        >
          {submitting ? "保存中..." : "保存する"}
        </button>
      </div>
      {error && <p className="text-sm text-red-600 mt-2">{error}</p>}
    </form>
  );
}
'''

INBOX_CLIENT_CONTENT = '''"use client";

import { useCallback, useEffect, useState } from "react";
import { apiFetch } from "@/lib/auth/client";
import { QuickCaptureForm } from "@/components/capture/QuickCaptureForm";

interface CaptureListItem {
  id: string;
  sourceType: string;
  rawText: string | null;
  processingStatus: string;
  domainId: string | null;
  sourceCapturedAt: string | null;
  version: number;
  createdAt: string;
}

interface CaptureDetail extends CaptureListItem {
  audioObjectKey: string | null;
  consentId: string | null;
  updatedAt: string;
}

interface InferenceItem {
  id: string;
  inferenceType: string;
  confidence: string;
  decision: string;
  createdAt: string;
}

const STATUS_LABEL: Record<string, string> = {
  SAVED: "保存済み",
  QUEUED: "解析待ち",
  PROCESSING: "解析中",
  READY: "候補あり",
  FAILED: "解析失敗",
};

const STATUS_STYLE: Record<string, string> = {
  SAVED: "bg-canvas text-muted",
  QUEUED: "bg-decide-50 text-decide",
  PROCESSING: "bg-ai-50 text-ai",
  READY: "bg-safe-50 text-safe",
  FAILED: "bg-warn-50 text-warn",
};

const SOURCE_TYPE_LABEL: Record<string, string> = {
  TEXT: "テキスト",
  VOICE: "音声",
  MEETING: "会議",
  IMPORT: "取込",
};

/** UI-04 Inbox: 原文から責任候補を確認する画面(API-CAP-01〜04と接続)。 */
export function InboxClient() {
  const [captures, setCaptures] = useState<CaptureListItem[]>([]);
  const [loadingList, setLoadingList] = useState(true);
  const [selectedId, setSelectedId] = useState<string | null>(null);
  const [detail, setDetail] = useState<CaptureDetail | null>(null);
  const [inferences, setInferences] = useState<InferenceItem[]>([]);
  const [loadingDetail, setLoadingDetail] = useState(false);
  const [analyzing, setAnalyzing] = useState(false);
  const [error, setError] = useState("");

  const loadList = useCallback(async () => {
    setLoadingList(true);
    const res = await fetch("/api/v1/captures");
    if (res.ok) {
      const body = await res.json();
      const items: CaptureListItem[] = body.data.captures;
      setCaptures(items);
      setSelectedId((current) => current ?? items[0]?.id ?? null);
    }
    setLoadingList(false);
  }, []);

  const loadDetail = useCallback(async (id: string) => {
    setLoadingDetail(true);
    setError("");
    const [detailRes, inferRes] = await Promise.all([
      fetch(`/api/v1/captures/${id}`),
      fetch(`/api/v1/captures/${id}/inferences`),
    ]);
    if (detailRes.ok) {
      const body = await detailRes.json();
      setDetail(body.data.capture);
    }
    if (inferRes.ok) {
      const body = await inferRes.json();
      setInferences(body.data.inferences);
    }
    setLoadingDetail(false);
  }, []);

  useEffect(() => {
    loadList();
  }, [loadList]);

  useEffect(() => {
    if (selectedId) loadDetail(selectedId);
  }, [selectedId, loadDetail]);

  async function requestAnalyze() {
    if (!selectedId) return;
    setAnalyzing(true);
    setError("");
    try {
      const res = await apiFetch(`/api/v1/captures/${selectedId}/analyze`, { method: "POST" });
      const body = await res.json();
      if (!res.ok) {
        setError(body.error?.message ?? "解析要求に失敗しました");
        return;
      }
      await Promise.all([loadDetail(selectedId), loadList()]);
    } finally {
      setAnalyzing(false);
    }
  }

  return (
    <div>
      <div className="mb-6">
        <h1 className="font-serif text-3xl">Inbox</h1>
        <p className="text-sm text-muted mt-1">原文を書き留め、責任として整理する前段の置き場です</p>
      </div>

      <div className="mb-6">
        <QuickCaptureForm onCreated={loadList} />
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-5 gap-5">
        <div className="lg:col-span-2 space-y-2">
          {loadingList && <p className="text-sm text-faint">読み込み中...</p>}
          {!loadingList && captures.length === 0 && (
            <div className="bg-surface border border-line rounded-xl p-4 text-sm text-muted">
              まだ何も書き留めていません。上の入力欄から最初のメモを保存してみてください。
            </div>
          )}
          {captures.map((c) => (
            <button
              key={c.id}
              onClick={() => setSelectedId(c.id)}
              className={`w-full text-left bg-surface rounded-xl p-3.5 transition ${
                selectedId === c.id ? "border-2 border-brand shadow-card" : "border border-line hover:border-ink/20"
              }`}
            >
              <div className="flex items-center justify-between mb-1 gap-2">
                <span className="text-[11px] font-mono text-faint truncate">
                  {SOURCE_TYPE_LABEL[c.sourceType] ?? c.sourceType} ・ {new Date(c.createdAt).toLocaleString("ja-JP")}
                </span>
                <span
                  className={`shrink-0 text-[10px] px-1.5 py-0.5 rounded font-mono ${
                    STATUS_STYLE[c.processingStatus] ?? "bg-canvas text-muted"
                  }`}
                >
                  {STATUS_LABEL[c.processingStatus] ?? c.processingStatus}
                </span>
              </div>
              <p className="text-sm line-clamp-2">{c.rawText || "(本文なし・音声のみ)"}</p>
            </button>
          ))}
        </div>

        <div className="lg:col-span-3">
          {!selectedId && <div className="text-sm text-faint">左の一覧から項目を選んでください</div>}
          {selectedId && loadingDetail && <p className="text-sm text-faint">読み込み中...</p>}
          {selectedId && !loadingDetail && detail && (
            <div className="bg-surface border border-line rounded-2xl shadow-card p-5 space-y-4">
              <div className="flex items-center justify-between">
                <span
                  className={`text-[11px] px-2 py-1 rounded font-mono ${
                    STATUS_STYLE[detail.processingStatus] ?? "bg-canvas text-muted"
                  }`}
                >
                  {STATUS_LABEL[detail.processingStatus] ?? detail.processingStatus}
                </span>
                <span className="text-[11px] text-faint font-mono">
                  {SOURCE_TYPE_LABEL[detail.sourceType] ?? detail.sourceType} ・ v{detail.version}
                </span>
              </div>
              <p className="text-sm whitespace-pre-wrap">{detail.rawText || "(本文なし・音声のみ)"}</p>

              <div className="border-t border-line pt-4">
                <div className="flex items-center justify-between mb-2 gap-3">
                  <span className="text-xs font-mono tracking-wide text-faint">AI候補</span>
                  <button
                    onClick={requestAnalyze}
                    disabled={
                      analyzing ||
                      detail.processingStatus === "QUEUED" ||
                      detail.processingStatus === "PROCESSING"
                    }
                    className="text-xs border border-line rounded-lg px-3 py-1.5 hover:bg-canvas disabled:opacity-40 transition"
                  >
                    {analyzing ? "要求中..." : "解析を要求する"}
                  </button>
                </div>
                {inferences.length === 0 ? (
                  <p className="text-xs text-faint">
                    候補はまだありません。AI Workerは未実装のため、解析要求後もこの一覧は空のままです(次回実装予定)。
                  </p>
                ) : (
                  <ul className="space-y-2">
                    {inferences.map((inf) => (
                      <li key={inf.id} className="bg-ai-50 rounded-lg p-3 text-xs">
                        <span className="font-mono text-ai">{inf.inferenceType}</span>
                        <span className="ml-2 text-muted">確度 {inf.confidence}</span>
                      </li>
                    ))}
                  </ul>
                )}
              </div>
              {error && <p className="text-sm text-red-600">{error}</p>}
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
'''

TODAY_CLIENT_CONTENT = '''"use client";

import { useCallback, useEffect, useState } from "react";
import Link from "next/link";
import { QuickCaptureForm } from "@/components/capture/QuickCaptureForm";

interface CaptureListItem {
  id: string;
  processingStatus: string;
}

/**
 * UI-03 ホーム／今日。
 * [既知の制約] 「今やる一つ」の算出にはResponsibility API・Planning API
 * (/planning/now)が必要だが未実装のため、設計書5章の空状態指針に従い
 * 正直な空状態＋Inboxへの導線を表示するに留める。
 */
export function TodayClient() {
  const [captures, setCaptures] = useState<CaptureListItem[]>([]);
  const [loading, setLoading] = useState(true);

  const load = useCallback(async () => {
    setLoading(true);
    const res = await fetch("/api/v1/captures?limit=100");
    if (res.ok) {
      const body = await res.json();
      setCaptures(body.data.captures);
    }
    setLoading(false);
  }, []);

  useEffect(() => {
    load();
  }, [load]);

  const unprocessedCount = captures.filter((c) => c.processingStatus === "SAVED").length;

  return (
    <div className="space-y-6">
      <div>
        <p className="text-xs text-faint font-mono mb-1">
          {new Date().toLocaleDateString("ja-JP", {
            year: "numeric",
            month: "long",
            day: "numeric",
            weekday: "short",
          })}
        </p>
        <h1 className="font-serif text-3xl">今日</h1>
      </div>

      <QuickCaptureForm onCreated={load} />

      <div className="bg-surface border border-line rounded-2xl shadow-card overflow-hidden">
        <div className="px-5 pt-4 pb-3 border-b border-line">
          <span className="text-xs font-mono tracking-wide text-faint">今やる一つ</span>
        </div>
        <div className="p-5">
          <p className="text-sm text-muted">
            「今やる一つ」を計算するには、責任(タスク・約束・判断)としての登録がまだ必要です。
            現在はメモの保存とInboxでの確認までが実装済みです。
          </p>
          <Link href="/inbox" className="inline-block mt-3 text-sm text-brand-700 font-medium hover:underline">
            Inboxで整理する →
          </Link>
        </div>
      </div>

      <div className="bg-surface border border-line rounded-2xl shadow-card p-5">
        <span className="text-xs font-mono tracking-wide text-faint">Inbox状況</span>
        {loading ? (
          <p className="text-sm text-faint mt-2">読み込み中...</p>
        ) : (
          <p className="text-sm text-ink mt-2">
            未整理の入力が <span className="font-semibold">{unprocessedCount}</span> 件、合計{" "}
            <span className="font-semibold">{captures.length}</span> 件を保存済みです。
          </p>
        )}
      </div>
    </div>
  );
}
'''

INBOX_PAGE_CONTENT = '''import { AppShell } from "@/components/app/AppShell";
import { InboxClient } from "@/components/capture/InboxClient";

export default function InboxPage() {
  return (
    <AppShell>
      <InboxClient />
    </AppShell>
  );
}
'''

TODAY_PAGE_CONTENT = '''import { AppShell } from "@/components/app/AppShell";
import { TodayClient } from "@/components/capture/TodayClient";

export default function TodayPage() {
  return (
    <AppShell>
      <TodayClient />
    </AppShell>
  );
}
'''


def apply_patches() -> None:
    print("\n=== パッチ適用 ===")

    backup(GLOBALS_CSS_PATH)
    GLOBALS_CSS_PATH.write_text(NEW_GLOBALS_CSS, encoding="utf-8")
    print(f"[PATCH] {GLOBALS_CSS_PATH} : ISMAY設計トークンへ置き換え")

    backup(LAYOUT_PATH)
    LAYOUT_PATH.write_text(NEW_LAYOUT_TSX, encoding="utf-8")
    print(f"[PATCH] {LAYOUT_PATH} : フォント(Newsreader/Inter/IBM Plex Mono)・タイトルを反映")

    backup(PAGE_PATH)
    PAGE_PATH.write_text(NEW_PAGE_TSX, encoding="utf-8")
    print(f"[PATCH] {PAGE_PATH} : create-next-appボイラープレート→/todayへのリダイレクト")

    backup(DASHBOARD_CLIENT_PATH)
    dashboard_text = DASHBOARD_CLIENT_PATH.read_text(encoding="utf-8")
    dashboard_text = dashboard_text.replace(DASHBOARD_IMPORT_MARKER, DASHBOARD_IMPORT_REPLACEMENT, 1)
    dashboard_text = dashboard_text.replace(DASHBOARD_HEADER_MARKER, DASHBOARD_HEADER_REPLACEMENT, 1)
    DASHBOARD_CLIENT_PATH.write_text(dashboard_text, encoding="utf-8")
    print(f"[PATCH] {DASHBOARD_CLIENT_PATH} : 「今日の画面へ」導線を追加")

    write_new_file(APP_SHELL_PATH, APP_SHELL_CONTENT)
    write_new_file(QUICK_CAPTURE_PATH, QUICK_CAPTURE_CONTENT)
    write_new_file(INBOX_CLIENT_PATH, INBOX_CLIENT_CONTENT)
    write_new_file(TODAY_CLIENT_PATH, TODAY_CLIENT_CONTENT)
    write_new_file(INBOX_PAGE_PATH, INBOX_PAGE_CONTENT)
    write_new_file(TODAY_PAGE_PATH, TODAY_PAGE_CONTENT)


def verify() -> None:
    print("\n=== 検証(コンパイルエラー0件が確認できた場合のみpushします) ===")
    run(["npx", "tsc", "--noEmit"], APP_DIR, "tsc --noEmit")
    print("\n[OK] tsc --noEmit エラー0件。")


def cleanup_backups_and_self() -> None:
    print("\n=== 後始末(push前に実行。前回の反省を反映) ===")
    for _orig, backup_path in backup_files:
        if backup_path.exists():
            backup_path.unlink()
            print(f"[CLEANUP] {backup_path} を削除")
    self_path = Path(__file__).resolve()
    print(f"[CLEANUP] {self_path} を削除(git add前に削除するためコミットに含まれない)")
    self_path.unlink()


def ship() -> None:
    print("\n=== GitHubへpush ===")
    run(["git", "add", "-A"], BASE_DIR, "git add")
    run(
        [
            "git", "commit", "-m",
            (
                "feat(ui): UI-03(今日)・UI-04(Inbox)画面を実装\n\n"
                "- globals.css/layout.tsx: 画面UX設計書v2.1のデザイントークンを反映\n"
                "- page.tsx: create-next-appボイラープレート→/todayへリダイレクト\n"
                "- components/app/AppShell.tsx: 認証ガード付き共通シェル(サイドバー)\n"
                "- components/capture/QuickCaptureForm.tsx: クイック入力(両画面で共用)\n"
                "- components/capture/InboxClient.tsx: UI-04本体。Capture API一式と接続\n"
                "  (一覧・詳細・解析要求。AI候補欄はAI Worker未実装のため空表示)\n"
                "- components/capture/TodayClient.tsx: UI-03本体。今やる一つは\n"
                "  Responsibility/Planning API未実装のため正直な空状態+Inbox導線を表示\n"
                "- DashboardClient.tsx: 「今日の画面へ」導線を追加\n\n"
                "スコープ外(次回対応): AI Worker、Responsibility API、Planning API、\n"
                "UI-05以降の画面"
            ),
        ],
        BASE_DIR, "git commit",
    )
    run(["git", "push"], BASE_DIR, "git push")
    print("\n[OK] GitHubへpush完了しました。")


def main() -> None:
    check_preconditions()
    apply_patches()
    verify()
    cleanup_backups_and_self()
    ship()
    print("\n=== 完了 ===")
    print("UI-03(今日)・UI-04(Inbox)画面の追加・検証・GitHub pushが完了しました。")
    print("schema.prisma変更は無いため、サービス再起動は不要です")
    print("(Next.js Fast Refreshで自動反映されます)。")
    print("\n次の確認: ブラウザで http://192.168.1.11:13000/today および /inbox を開き、")
    print("クイック入力欄からメモを保存できること、Inbox一覧に反映されることを確認してください。")


if __name__ == "__main__":
    main()
